/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontSize: {
        'h1-sm': '16px',
        'h1-md': '24px',
        'h1-lg': '32px',
        'h1-xl': '40px',
        'h1-2xl': '48px',
        'h2-sm': '14px',
        'h2-md': '22px',
        'h2-lg': '30px',
        'h2-xl': '38px',
        'h2-2xl': '46px',
        'h3-sm': '12px',
        'h3-md': '20px',
        'h3-lg': '28px',
        'h3-xl': '30px',
        'h3-2xl': '44px',
        'body-sm': '12px',
        'body-md': '20px',
        'body-lg': '28px',
        'body-xl': '36px',
        'body-2xl': '44px',
      },
      spacing: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
      },
      colors: {
        'background-page': '#F9FAFB',
        'background-primary': '#FFFFFF',
        'background-secondary': '#F3F4F6',
        'text-heading': '#111111',
        'text-label': '#6B7280',
        'text-muted': '#4B5563',
        'text-subtle': '#9CA3AF',
        'text-link': '#3B82F6',
        'text-error': '#DC2626',
        'text-success': '#16A34A',
        'accent-primary': '#000000',
        'accent-secondary': '#E5E7EB',
        'accent-yellow': '#FBBF24',
        'accent-blue': '#93C5FD',
      },
      boxShadow: {
        sm: '2px 2px 2px rgba(0,0,0,0.1)',
        md: '3px 3px 3px rgba(0,0,0,0.15)',
        lg: '4px 4px 4px rgba(0,0,0,0.2)',
        xl: '5px 5px 5px rgba(0,0,0,0.25)',
        '2xl': '6px 6px 6px rgba(0,0,0,0.3)',
        inner: 'inset 2px 2px 4px rgba(0,0,0,0.1)',
      },
      borderRadius: {
        lg: '0.5rem',
        xl: '1rem',
        '2xl': '1.5rem',
      }
    },
  },
  plugins: [],
};
